---
title: "Getting started with qgisprocess"
author: "Jannes Muenchow & Floris Vanderhaeghe"
date: |
  | Last update: 2024-02-21
  | Last run: `r Sys.Date()`
output:
  html_document: 
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: no
    toc_depth: 2
vignette: >
  %\VignetteIndexEntry{Basic usage of qgisprocess}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
can_build <- qgisprocess::has_qgis() &&
  # 'grass7' provider label has changed to 'grass' in 3.35 (dev)
  package_version(qgisprocess::qgis_version(full = FALSE)) >= "3.35.0" &&
  all(qgisprocess::qgis_has_plugin(c(
    "grassprovider",
    "processing_saga_nextgen"
  ))) &&
  requireNamespace("spDataLarge", quietly = TRUE) &&
  requireNamespace("sf", quietly = TRUE) &&
  requireNamespace("terra", quietly = TRUE) &&
  requireNamespace("mapview", quietly = TRUE)
```

```{r child=if (can_build) file.path(rprojroot::find_root(rprojroot::is_r_package), "man/vignette_childs/_qgisprocess.Rmd")}
```

```{r eval=!can_build, echo=FALSE, results="asis"}
cat("This vignette has been built in absence of a QGIS installation, with a missing QGIS plugin, or in absence of the spDataLarge, sf, terra or mapview package.\n\n")
cat("Read it online at <https://r-spatial.github.io/qgisprocess/articles/qgisprocess.html>.")
```
