---
title: "2. Use case: predicting plant species richness on Mt. Mongón"
author: "Jannes Muenchow"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 2
vignette: >
  %\VignetteIndexEntry{"2. Use case: predicting plant species richness on Mt. Mongón"}
  %\VignetteEngine{knitr::knitr}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r sinkremoval, eval=FALSE}
library("dplyr")
library("qgisprocess")
library("raster")
library("sf")
library("terra")
data(dem, study_area, ndvi, random_points, package = "spDataLarge")
dem = dem / 1000
my_poly = poly(values(dem), degree = 2)
dem1 = dem2 = dem
values(dem1) = my_poly[, 1]
values(dem2) = my_poly[, 2]
dn = c(rast(dem1), rast(dem2), rast(ndvi))
names(dn) = c("dem1", "dem2", "ndvi")
# crs(dn) = "epsg:32717"

qgis_arguments("saga:sinkremoval")
out = qgis_run_algorithm(
  algorithm = "saga:sinkremoval",
  DEM = dem, 
  METHOD = 1, 
  DEM_PREPROC = file.path(tempdir(), "sdem.sdat")
  )

sdem = raster(qgis_output(out, "DEM_PREPROC")[1])
qgis_show_help("saga:sagawetnessindex")
qgis_arguments("saga:sagawetnessindex")$available_values
outs = qgis_outputs("saga:sagawetnessindex")$name
out_nms = paste0(tempdir(), "/", outs, ".sdat")
args = rlang::set_names(out_nms, outs)
out = qgis_run_algorithm(
  algorithm = "saga:sagawetnessindex",
  DEM = file.path(tempdir(), "sdem.sdat"),
  SLOPE_TYPE = 1, AREA_TYPE = 0,
  !!!args)
# we are only interested in cslope and carea
s = c(rast(out$AREA[1]), rast(out$SLOPE[1]))
names(s) = c("log_carea", "cslope")
s$cslope = s$cslope * 180 /pi
s$log_carea = log(s$log_carea / 1e+06)
plot(s)
# this also changes the origin!!
ext(dn) = ext(s)
s = c(dn, s)

# data("ndvi", package = "spDataLarge")
# # raster::origin(ndvi) = terra::origin(s)
# raster::projection(ndvi) = st_crs(32717)$proj4string
# ndvi = rast(ndvi)
# # crs(ndvi) = crs(s$cslope)
# terra::ext(ndvi) = terra::ext(s)
# # this also changes the origin!!
# s = c(s, ndvi)
plot(s)
# fnms = paste0(tempdir(), "/", names(s), ".tif")
# terra::writeRaster(s, fnms, overwrite = TRUE)
# algs = qgis_algorithms()
# filter(algs, grepl("value", algorithm_title)) %>% as.data.frame
# qgisprocess::qgis_show_help("saga:addrastervaluestopoints")
# qgis_arguments("saga:addrastervaluestopoints")
# # args = rlang::set_names(fnms, rep("GRIDS", length(fnms)))
# out = qgis_run_algorithm(
#   "saga:addrastervaluestopoints",
#   SHAPES = random_points,
#   # multilayer objects are so far not supported as R objects
#   # GRIDS = s$log_carea,
#   # GRIDS = s$cslope,
#   # GRIDS = s$ndvi,
#   # !!!args,
#   GRIDS = file.path(tempdir(), "clsope.tif"),
#   GRIDS = file.path(tempdir(), "ndvi.tif"),
#   GRIDS = file.path(tempdir(), "log_carea.tif"),
#  # GRIDS = file.path(tempdir(), "dem1.sdat"),
#   #GRIDS = file.path(tempdir(), "dem2.sdat"),
#   #GRIDS = file.path(tempdir(), "dem2.sdat"),
#   RESAMPLING = 0,
#   RESULT = file.path(tempdir(), "vals.shp"))

vals = read_sf(qgis_output(out, "RESULT"))
vals = terra::extract(s, as(random_points, "SpatVector"))
vals = inner_join(random_points, vals, by = c("id" = "ID"))
fit = glm(formula = spri ~ dem1 + dem2 + cslope + ndvi + log_carea,
           data = vals,
           family = "poisson")

pred = predict(object = s,
                model = fit,
                fun = predict,
                type = "response")
pred = mask(x = pred, mask = as(study_area, "SpatVector"))
# plot the output (shown in Figure 5)
hs = raster::hillShade(terrain(dem), terra::terrain(dem, "aspect")) |>
  raster::mask(mask = study_area)
plot(hs, col = gray(seq(0, 1, length.out = 100)), legend = FALSE,
     xlim = c(795000, 797500), ylim = c(8932000, 8935000))
plot(raster(pred), col = RColorBrewer::brewer.pal(name = "YlOrRd", n = 9),
     add = TRUE, alpha = 0.8)
plot(st_geometry(random_points), add = TRUE)

```

Same as `terra::extract(s, as(random_points, "SpatVector"))`.

<!--
## ------------------------------------------------------------------------
get_usage("saga:sinkremoval")
run_qgis(alg = "saga:sinkremoval",
         DEM = dem, 
         METHOD = "[1] Fill Sinks", 
         DEM_PREPROC = file.path(tempdir(), "sdem.sdat"),
         show_output_paths = FALSE)

## ------------------------------------------------------------------------
get_usage("saga:sagawetnessindex")
run_qgis(alg = "saga:sagawetnessindex",
         DEM = file.path(tempdir(), "sdem.sdat"),
         SLOPE_TYPE = 1, 
         SLOPE = file.path(tempdir(), "cslope.sdat"),
         AREA = file.path(tempdir(), "carea.sdat"),
         show_output_paths = FALSE)

## ----eval = FALSE--------------------------------------------------------
library("dplyr")
library("raster")
file.path(tempdir(), c("cslope.sdat", "carea.sdat")) %>%
  raster::stack(.) %>%
  plot

## ----message = FALSE, error = FALSE, warning = FALSE---------------------
library("raster")
cslope <- raster(file.path(tempdir(), "cslope.sdat"))
cslope <- cslope * 180 /pi

## ------------------------------------------------------------------------
carea <- raster(file.path(tempdir(), "carea.sdat"))
log_carea <- log(carea / 1e+06)

## ------------------------------------------------------------------------
data("ndvi", package = "RQGIS")

## ----eval = TRUE, cache = FALSE, message = FALSE, error = FALSE, warning = FALSE----
data("dem", package = "RQGIS")
dem <- dem / 1000
my_poly <- poly(values(dem), degree = 2)
dem1 <- dem2 <- dem
values(dem1) <- my_poly[, 1]
values(dem2) <- my_poly[, 2]
for (i in c("dem1", "dem2", "log_carea", "cslope", "ndvi")) {
  tmp <- crop(get(i), dem) 
  writeRaster(x = tmp, 
              filename = file.path(tempdir(), paste0(i, ".asc")), 
              format = "ascii",
              prj = TRUE,
              overwrite = TRUE)  
}

## ----eval = TRUE, cache = FALSE, message = FALSE-------------------------
library("dplyr")
data("random_points", package = "RQGIS")
random_points[, c("x", "y")] <- sf::st_coordinates(random_points)
raster_names <- c("dem1", "dem2", "log_carea", "cslope", "ndvi")
vals <- RSAGA::pick.from.ascii.grids(data = as.data.frame(random_points),
                                     X.name = "x", 
                                     Y.name = "y", 
                                     file = file.path(tempdir(), raster_names),
                                     varname = raster_names)
dplyr::select(vals, -geometry) %>%
  head(., 3)

## ------------------------------------------------------------------------
fit <- glm(formula = spri ~ dem1 + dem2 + cslope + ndvi + log_carea,
           data = vals,
           family = "poisson")

## ----pred, eval = FALSE--------------------------------------------------
library("sf")
library("raster")
raster_names <- c("dem1.asc", "dem2.asc", "log_carea.asc", "cslope.asc",
                  "ndvi.asc")
s <- stack(x = file.path(tempdir(), raster_names))
pred <- predict(object = s,
                model = fit,
                fun = predict,
                type = "response")
pred <- crop(x = pred,
             y = as(random_points, "Spatial"))
# plot the output (shown in Figure 5)
plot(pred)
plot(st_geometry(random_points), add = TRUE)

-->
